### PR TITLE
fix deprecation error

### LINKED ISSUE #136: PHP Deprecated: Return type of Bulletproof\Image
Getting 4 Deprecated-Warnings when using Bulletproof:

```
PHP Deprecated:  Return type of Bulletproof\Image::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <PATH>\bulletproof.php on line 124
PHP Deprecated:  Return type of Bulletproof\Image::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <PATH>\bulletproof.php on line 140
PHP Deprecated:  Return type of Bulletproof\Image::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <PATH>\bulletproof.php on line 117
PHP Deprecated:  Return type of Bulletproof\Image::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <PATH>\bulletproof.php on line 131
```

Version 5.0.0
PHP-Version: 8.1.12

### PR DESCRIPTION
**Pull request by samayo**
fixes #136

### CODE REVIEW

File: src/bulletproof.php [hunk 1]
```diff
@@ -114,21 +114,21 @@ public function __construct(array $_files = array())
...
-    public function offsetSet($offset, $value) {}
+    public function offsetSet($offset, $value) : void {}
 
     /**
      * \ArrayAccess unused method
      * 
      * @param mixed $offset
      */
-    public function offsetExists($offset){}
+    public function offsetExists($offset) : bool {}
```
Comment (DominikTV) [inline src/bulletproof.php:124]: There seems to be not return statement when an bool is expected.

Comment (samayo) [reply src/bulletproof.php:124]: That's the correct return type for the method. Are you getting errors?
